[package]
name = "rust-dbus-rqrng-service"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus="5.1.1"
tokio = { version = "1.41.1", features = ["full"] }
env_logger = "0.11.5"
libc = "0.2"
log = "0.4.22"
cfg-if = "1.0.0"