[sources]
combine="xor"

[[sources.lrng]]
id="linux-dev-random"
enabled=true
buffer_mebibytes=128

[[sources.file]]
id="idq-quantis"
enabled=false
path="/dev/qrandom0"
buffer_mebibytes=128

[[sources.file]]
id="some-file"
enabled=false
path="some_file.bin"
loop=true